"""
src/scripter.py - Script Writer for The Financial Hero
"""
import os
import logging
import random

log = logging.getLogger(__name__)

SYSTEM_PROMPT = """You write viral YouTube Shorts scripts for a personal finance channel called The Financial Hero.
Rules:
- Write exactly 130 to 150 words — this must be spoken aloud in 50 to 60 seconds.
- Structure: Hook (1 shocking sentence) → Problem (2 sentences) → Solution (2-3 sentences) → Call to action (1 sentence).
- Open with a shocking money hook that stops the scroll.
- End with a powerful truth or call to action that makes viewers want to save or share.
- Plain text only, no emojis, no hashtags, no stage directions, no bullet points.
- Write as if speaking directly to one person about their financial future.
- Every sentence must flow naturally when spoken aloud."""

# 40 viral script topics
FINANCE_TOPICS = [
    "why you're still broke even though you work every day",
    "saving money won't make you rich",
    "the paycheck trap most people never escape",
    "rich versus poor thinking",
    "small daily habits that build massive wealth",
    "comfort is slowly destroying your future",
    "stop waiting for the perfect time to start",
    "discipline beats motivation every time",
    "the lifestyle trap that keeps you broke",
    "how small actions create massive change over time",
    "why starting early changes your entire life",
    "why most people fail and how to avoid it",
    "action versus thinking — what actually creates results",
    "small expenses that are secretly destroying your money",
    "how your circle decides your financial future",
    "discipline feels hard but gives you freedom",
    "focus is the most valuable skill you can build",
    "delay gratification and win long term",
    "stop comparing yourself to others",
    "build assets instead of buying liabilities",
    "how debt is a trap most people don't see",
    "learn daily or fall behind",
    "why consistent investing beats everything",
    "spend money with purpose not emotion",
    "track your money or lose it",
    "lifestyle inflation keeps you stuck no matter your income",
    "short term thinking keeps you poor",
    "patience is a financial superpower",
    "consistency beats talent every time",
    "grow one percent better every single day",
    "your habits are building your future right now",
    "time is more valuable than money",
    "stop wasting energy on the wrong things",
    "think bigger and your life expands",
    "distractions are stealing your financial future",
    "control your emotions or they control your money",
    "deep focus creates results faster than anything else",
    "smart risks create opportunity and growth",
    "failure teaches what success never could",
    "keep going because most people quit too early",
]

# 40 viral scripts — one per topic, clean plain text for TTS
VIRAL_SCRIPTS = {
    "why you're still broke even though you work every day": "Why are you still broke even though you work every single day. It is not your job. It is not your salary. It is your habits. Every day you make small money decisions without thinking. Buying things you do not need. Paying for subscriptions you do not use. Spending just because it feels good in the moment. Individually they seem small. But over time they control your entire financial life. Now imagine flipping that habit. Instead of spending first you invest first. Even five dollars. Even ten dollars. Done daily it compounds. That is the real difference between staying broke and building wealth. You do not need more money. You need better habits. Start today, track every dollar you spend, and watch how fast your financial life begins to change for the better.",

    "saving money won't make you rich": "Saving money will not make you rich and almost nobody tells you this truth. Saving feels safe. You put money in your account and you feel responsible. But here is the truth. Inflation is quietly eating your money every single year. So even if your balance increases your actual purchasing power decreases. Now look at investing. Your money works. It grows. It compounds over time. That is why wealthy people do not just save. They invest consistently month after month regardless of market conditions. Saving protects money in the short term. Investing multiplies money over the long term. The wealthy understand this difference and act on it every single month. If you want to build real wealth you have to move beyond saving and start putting your money into assets that grow faster than inflation destroys them.",

    "the paycheck trap most people never escape": "Most people are trapped in a cycle and they do not even realize it. Work. Get paid. Spend. Repeat. That is the cycle most people live in their entire lives. No growth. No freedom. You are trading your time for money but never building anything for yourself. Meanwhile wealthy people do something completely different. They build assets. Assets that pay them even when they are not working. A rental property pays rent. Index funds pay dividends. A business generates income without requiring your presence every hour. That is the real difference between being an employee and being financially free. If you only work for money you will always need to work. The goal is to build things that work for you. Start small. Start now. And begin shifting from spending your paycheck to investing even a small portion of it every single month.",

    "rich versus poor thinking": "The difference between rich and poor people is not talent or luck. It is how they think about money. A poor mindset asks how much does this cost. A rich mindset asks how much will this make me. One focuses entirely on spending. The other focuses entirely on return. Same amount of money. Completely different decisions. And over time those small daily decisions compound into completely different lives. Rich thinkers see a course and ask what skills will this build. Poor thinkers see the same course and say I cannot afford that. Rich thinkers invest in assets. Poor thinkers buy liabilities. The beautiful thing is that thinking is a skill. And skills can be learned. Change how you think about every financial decision you make and you will gradually change the direction and quality of your entire financial future.",

    "small daily habits that build massive wealth": "Your life right now is built entirely by your daily habits. Not your goals. Not your intentions. Your habits. What you do every single day builds your future automatically whether you realize it or not. Spend ten dollars every day and it disappears. Invest ten dollars every day and it grows into something significant over time. Same amount of money. Completely different result. The secret to building wealth is not big dramatic moves. It is consistency. Small actions repeated daily create massive change over time. The wealthy did not get wealthy overnight. They built small disciplined habits and repeated them for years. Wake up earlier. Spend less than you earn. Invest the difference automatically. Learn something new every week. These small habits done consistently will create a financial life most people only dream about.",

    "comfort is slowly destroying your future": "Comfort is slowly destroying your financial future and most people never see it coming. Easy choices feel good right now. Scrolling. Watching. Spending without thinking. But every easy decision you make today comes with a hidden cost you pay tomorrow. Meanwhile hard choices feel uncomfortable in the moment but they build discipline. And discipline builds freedom. Most people choose comfort every single day. That is exactly why most people stay stuck financially their entire lives. The people who build real wealth are not smarter or luckier than you. They simply chose discipline when it was uncomfortable. They invested when they wanted to spend. They learned when they wanted to scroll. They acted when they wanted to wait. Comfort now means struggle later. Discipline now means freedom later. Choose which one you want and then act accordingly every single day.",

    "stop waiting for the perfect time to start": "Stop waiting for the perfect time because it does not exist and it never will. You will always feel unready. You will always have doubts. There will always be a reason to delay starting. But waiting does not improve your life. Action does. Every successful person you admire started before they felt ready. They did not wait for perfect conditions. They moved with what they had and figured things out along the way. The longer you wait the further you fall behind. Compound interest rewards those who start early and punishes those who wait. Five years of investing in your twenties is worth more than fifteen years of investing in your forties. Time is the one resource you cannot get back. Whatever you have been putting off starting today is the day to begin. Start small. Start imperfect. But start.",

    "discipline beats motivation every time": "Motivation is unreliable and that is the real problem most people face. Some days you feel motivated to work hard and invest and build. Most days you simply do not feel like it. And that is completely normal. But discipline does not depend on feelings. Discipline shows up anyway regardless of how you feel. That is exactly why disciplined people build wealth and motivated people stay stuck waiting to feel inspired. Wealthy investors do not invest only when markets look exciting. They invest every month automatically whether they feel like it or not. Successful entrepreneurs do not work only when they feel creative. They show up and do the work daily. Discipline is not about being perfect. It is about showing up consistently even when you do not feel like it. Build your discipline and your financial future will build itself.",

    "the lifestyle trap that keeps you broke": "Your lifestyle is quietly keeping you broke and most people never realize it until it is too late. Every upgrade feels exciting and justified. Better phone. Better clothes. Better car. Better apartment. But every upgrade adds financial pressure. More spending means less freedom. You start looking wealthy from the outside while becoming more trapped on the inside. The scary truth is that most people who look rich are actually living paycheck to paycheck because their lifestyle costs exceed their income. Real wealth looks boring from the outside. It is driving a normal car while your investments grow. It is wearing simple clothes while your savings compound. It is saying no to lifestyle upgrades so you can say yes to financial freedom later. Looking rich is not being rich. Choose the one that actually matters for your future.",

    "how small actions create massive change over time": "Want to change your financial life. Start smaller than you think you need to. Most people wait for a big moment to make a dramatic change. But real lasting change comes from tiny consistent actions repeated over long periods of time. Wake up thirty minutes earlier every day. That is over one hundred hours of extra productive time per year. Invest fifty dollars every week. That becomes over two thousand dollars annually working and compounding for your future. Learn one new financial concept every week. That is fifty new ideas per year reshaping how you think about money. None of these feel significant in the moment. But compounded over years they create completely different outcomes. Small actions done consistently are the most underrated wealth building strategy that exists. Start smaller than feels meaningful and stay consistent longer than feels necessary.",

    "why starting early changes your entire life": "Starting early can change your entire financial life and the math behind it is staggering. Most people think they need a lot of money to start investing. But what you really need is time. Because time is what makes money grow exponentially. When you invest early your money compounds. It earns and then earns again on top of previous earnings. But when you start late you have to work twice as hard to reach the same result. Two people with identical incomes can end up in completely different financial places simply because one started investing at twenty two and the other waited until thirty five. That thirteen year difference can mean hundreds of thousands of dollars in final wealth. Time is your biggest financial advantage when you are young. Use it. Start investing something today even if it feels too small to matter because starting is everything.",

    "why most people fail and how to avoid it": "Most people do not fail because they are not smart enough or talented enough. They fail because they quit too early. Success in building wealth does not happen quickly. It takes time. It takes consistent effort. It takes staying in the game long enough for compound growth to work its magic. But quitting is easy and it always feels justified in the moment. Markets drop and people sell. Progress slows and people stop. Results take longer than expected and people give up. That is why success looks rare. Not because it is impossible but because most people do not stay consistent long enough. The breakthrough in investing almost always comes after a long boring period where nothing seems to be working. Stay longer than others quit. Keep investing when others panic. Keep building when others stop. That single habit will separate your financial future from everyone around you.",

    "action versus thinking — what actually creates results": "Thinking about building wealth will not make you wealthy. Planning feels productive. You research investment options. You read about strategies. You think you are making progress. But nothing in your bank account actually changes until you take real action. Ideas and plans do not create financial results. Execution does. And the longer you spend thinking without acting the harder it becomes to start because perfectionism grows stronger with every passing day. The most successful investors are not the ones with the best strategies. They are the ones who started with an imperfect plan and adjusted as they went. Open that investment account today. Make that first deposit this week. Set up that automatic transfer right now. You do not need a perfect plan. You need a start. Less thinking. More doing. Your financial future is built by actions not intentions.",

    "small expenses that are secretly destroying your money": "Small expenses are secretly destroying your financial future and they are almost invisible until you add them up. It is never one big purchase that causes the problem. It is the small daily things. Daily coffee runs. Unused streaming subscriptions. Impulse buys that feel harmless in the moment. Food delivery fees adding up every week. None of these feel dangerous individually. But together they can drain hundreds or even thousands of dollars every single month from your financial future. Money you could have invested and allowed to compound over decades is simply gone with nothing to show for it. The solution is awareness. Track every single purchase for thirty days and you will be shocked at where your money is actually going. Then redirect even half of that spending toward investments. Small leaks sink large ships. Control the small expenses and you control your entire financial trajectory.",

    "how your circle decides your financial future": "Look at the five people you spend the most time with and you will see your financial future. Habits are more contagious than most people realize. If the people around you spend freely you will spend freely. If they invest consistently you will feel motivated to invest. If they think small about money you will unconsciously think small too. You do not rise above your environment. You gradually become a reflection of it. That is why the most important financial decision you can make is choosing who you spend your time with. Find people who talk about investing not just spending. Find people who are building assets not just buying things. Find people whose financial habits you want to develop. You are not stuck with your current circle. But you are heavily influenced by it every single day. Change your environment and you change your financial destiny.",

    "discipline feels hard but gives you freedom": "Discipline feels hard in the moment and that is exactly why most people avoid it. Waking up early when you could sleep in. Investing money when you want to spend it. Saying no to things that feel enjoyable right now. These actions feel uncomfortable and even pointless in the short term. But here is what nobody tells you. Discipline is the price you pay for freedom. Every disciplined financial choice you make today buys you more freedom tomorrow. The person who invests consistently for twenty years buys the freedom to stop working if they choose. The person who controls their spending buys the freedom from financial stress. The person who learns valuable skills buys freedom from being stuck in a job they hate. Discipline now is freedom later. Every single time without exception. The question is simply whether you are willing to pay the short term price for the long term reward.",

    "focus is the most valuable skill you can build": "Focus is one of the most valuable and rare skills in today's world and most people are losing it every single day. We live in an environment deliberately designed to pull your attention in a hundred directions simultaneously. Notifications. Algorithms. Endless content created specifically to keep you distracted. But building wealth requires sustained focused attention. Learning about investing requires focus. Building a business requires focus. Developing financial skills requires focus. When you can focus deeply you make progress faster than almost anyone around you. When you are constantly distracted you stay stuck while others advance. Protect your attention like it is your most valuable financial asset because it actually is. Turn off notifications. Schedule deep work sessions. Learn to sit with discomfort instead of reaching for distraction. Where your focused attention consistently goes your financial results will eventually follow.",

    "delay gratification and win long term": "If you want to build real wealth learn one skill above all others. Delay gratification. Most people choose pleasure right now over wealth later. Spending today instead of investing. Relaxing today instead of building. Avoiding discomfort today instead of developing skills that pay forever. But every wealthy person you admire made the opposite choice consistently over years. They sacrificed short term pleasure for long term financial gain. They drove a basic car while their wealth grew. They skipped expensive vacations while their investments compounded. They said no to lifestyle upgrades so they could say yes to financial freedom. The formula is simple even if the execution is hard. Give up something small today and receive something massive later. Short term sacrifice creates long term success every single time. Start practicing delayed gratification in small ways today and watch how dramatically your financial future begins to change.",

    "stop comparing yourself to others": "Comparison is silently destroying your financial progress and most people do not realize it is happening. You look at what others have and you feel behind. But you never see their full story. You see the car not the car payment. You see the vacation not the credit card debt. You see the lifestyle not the financial stress happening behind closed doors. Comparison creates pressure. And financial pressure leads to terrible decisions. Buying things you cannot afford to impress people you do not know. Taking on debt to match a lifestyle that was never real to begin with. Your financial journey is yours alone and it deserves your full attention. Every minute you spend comparing yourself to others is a minute stolen from building your own wealth. Focus on your own numbers. Your own progress. Your own goals. Compare less and you will progress more than you ever imagined possible.",

    "build assets instead of buying liabilities": "If you want to build real wealth you need to understand one simple distinction that changes everything. Assets versus liabilities. Most people spend their money on things that lose value the moment they buy them. Phones. Clothes. Cars. Luxury items. These are liabilities. They cost money to maintain and they decrease in value over time. Wealthy people think completely differently. They buy assets. Stocks that grow and pay dividends. Real estate that generates rental income. Businesses that produce revenue. Index funds that compound over decades. Assets generate income and increase in value over time. The wealthy are not smarter than you. They simply prioritize buying things that make them more money over things that make them look good. Every dollar you redirect from liabilities to assets is a dollar working for your future. Start building your asset base today even if you start very small.",

    "how debt is a trap most people don't see": "Debt looks completely normal in today's world and that is exactly what makes it so dangerous. Credit cards. Car loans. Buy now pay later. Monthly payments that seem manageable at first glance. But over time debt quietly takes control of your financial life. You stop working for your dreams and start working to pay off your past. Interest keeps growing silently in the background. Stress builds every month. And financial freedom gets pushed further and further into the future. Meanwhile people who avoided bad debt are investing that same money and watching it compound year after year. The difference between someone with debt and someone investing the equivalent amount for twenty years is extraordinary. Debt takes your future before you even get to live it. Start aggressively paying off any high interest debt you carry right now. Financial freedom begins the moment you stop letting past spending control your present income.",

    "learn daily or fall behind": "If you are not consistently learning new things you are falling behind financially and you probably do not even feel it yet. The world changes faster every single year. New opportunities emerge. Old skills become obsolete. New ways to earn and invest and grow your money appear regularly. But most people stop learning after school and stay locked in the same knowledge and the same income level for decades. Even twenty minutes of focused learning every single day adds up to over one hundred hours of new knowledge per year. One hundred hours of learning about investing, business, money psychology, or any valuable skill will dramatically change the quality of your financial decisions. The most successful investors and entrepreneurs never stop learning. They read constantly. They study obsessively. They treat knowledge like the most important investment they can make because it is the one investment that always pays returns.",

    "why consistent investing beats everything": "Consistent investing beats almost every other financial strategy that exists and the reason is mathematical. Most people wait for the perfect moment to invest. When markets look stable. When they have more money saved. When things feel less uncertain. But the perfect moment never arrives and while they wait time passes. Time that could have been spent compounding their wealth. Consistent investing means putting money in every single month regardless of market conditions. When prices are high you buy. When prices are low you buy more at a discount. Over long periods this strategy beats almost every attempt to time the market perfectly. Small amounts invested consistently over decades build extraordinary wealth. It is not exciting. It is not complicated. But it works better than almost anything else. Start a monthly automatic investment today in an index fund and never stop regardless of what markets do around you.",

    "spend money with purpose not emotion": "Every dollar you spend either moves you toward financial freedom or further from it. Most people spend money emotionally without any real intention or awareness. Impulse purchases triggered by stress or boredom or social pressure. Emotional buys that feel justified in the moment but leave you with nothing lasting. But when you spend money with clear purpose and intention everything changes. You decide in advance what your money is for. You align your spending with your actual values and goals. You stop buying things to feel better temporarily and start directing money toward things that build lasting security and freedom. This does not mean never enjoying money. It means being deliberately intentional about every significant financial decision you make. Ask yourself before every purchase whether it moves you closer to or further from the life you actually want. Intentional spending is the foundation of real financial control and eventually financial freedom.",

    "track your money or lose it": "If you do not track your money you will lose it and most people experience this truth without ever understanding why. Most people have almost no idea where their money actually goes each month. It disappears into small purchases and forgotten subscriptions and habitual spending that adds up to hundreds or thousands of dollars gone with nothing meaningful to show for it. Without tracking you are making financial decisions completely blind. And guessing about money always leads to mistakes. Tracking creates awareness. And awareness creates the ability to make intentional choices. When you see exactly where every dollar goes you can redirect even a fraction of wasted spending toward investments that grow. You do not have to track every penny forever. But do it for thirty days and the awareness you gain will permanently change how you think about and manage your money for the rest of your life.",

    "lifestyle inflation keeps you stuck no matter your income": "Making more money will not fix your financial problems if your lifestyle grows every time your income grows. This is called lifestyle inflation and it silently traps millions of people at every income level. You get a raise and immediately upgrade your apartment. You earn more and buy a better car. Your income doubles and somehow your savings stay exactly the same. More money flows in and more money flows out and nothing actually improves in your financial situation. Real financial progress comes from keeping your lifestyle relatively stable while your income grows. Every dollar of income growth that does not go into lifestyle upgrades can go directly into investments that compound for your future. This single discipline of controlling lifestyle inflation is responsible for more wealth creation than almost any other financial habit. Earn more. Keep spending the same. Invest the difference. Watch your financial life transform.",

    "short term thinking keeps you poor": "Short term thinking is one of the most expensive mental habits most people carry without realizing it. When you focus only on today you make decisions that feel good right now but cost you significantly later. Spending instead of investing because investing feels distant and abstract. Avoiding discomfort now instead of building skills that pay forever. Quitting when progress is slow instead of staying consistent long enough for compound growth to work. But long term thinking completely changes your financial decisions. When you think in decades instead of days investing becomes obvious. Delayed gratification becomes easier. Short term sacrifices feel worthwhile because you can clearly see the long term result they are building toward. The wealthiest people in the world are almost always the longest term thinkers in any room. Start extending your financial time horizon today and watch every money decision you make improve immediately.",

    "patience is a financial superpower": "Patience is one of the most underrated financial superpowers that exists and almost nobody develops it intentionally. We live in a world that promises instant results in every area of life. But real wealth is built slowly. Quietly. Over long periods of time without dramatic daily progress. Markets take time to grow. Businesses take years to become profitable. Skills take thousands of hours to develop into something valuable. People who stay patient through this slow growth phase end up with extraordinary results. People who demand fast results quit early and miss the compounding that happens in the later years. The last few years of a long investment horizon create more wealth than all the earlier years combined because of how compound growth accelerates. Develop patience as a deliberate financial skill. Celebrate slow steady progress. Trust the process of compounding. And let time work for you instead of feeling like an enemy.",

    "consistency beats talent every time": "You do not need to be the smartest person in the room to build wealth. You do not need to be the most talented investor or the best business mind. You simply need to show up and take action every single day regardless of results. Consistent small actions done repeatedly over long periods of time beat brilliant strategies done inconsistently every single time. The investor who puts in two hundred dollars every month for twenty years builds more wealth than the investor who tries to time the market perfectly with larger amounts. The person who reads about finance for thirty minutes every day builds more knowledge than someone who goes through intense learning phases followed by long periods of doing nothing. Consistency is the great equalizer. It rewards ordinary people with extraordinary results if they simply refuse to stop. Show up daily. Invest monthly. Learn weekly. And trust that consistency always wins in the end.",

    "grow one percent better every single day": "You do not need massive dramatic changes to transform your financial life. You just need to get one percent better every single day and let time do the rest. One percent improvement sounds almost meaningless. But compounded over a full year it creates a result that is thirty seven times better than where you started. Wake up thirty minutes earlier and use that time to learn about investing. That is over one hundred hours of financial education per year. Cut one unnecessary expense and redirect it to investments. That small habit compounds into significant wealth over a decade. Learn one new financial concept every week. By the end of the year you will think about money in ways that completely change your decisions and results. Small daily improvements feel insignificant in the moment but they are the most powerful wealth building strategy available to ordinary people. Start with one small improvement today and never stop.",

    "your habits are building your future right now": "Your financial future is not being built by your goals or your intentions or your dreams. It is being built right now by your daily habits whether you are aware of them or not. Every financial choice you make consistently becomes a habit. And habits compound just like money does. Good financial habits push your future forward automatically. Bad financial habits silently pull it backward without you noticing. The frightening thing about habits is that most of them run unconsciously. You spend without thinking. You delay investing without deciding to. You avoid learning about money without consciously choosing ignorance. But once you become aware of your financial habits you gain the power to change them deliberately. Identify one bad financial habit you repeat regularly and replace it with one good one. Do it consistently for sixty days. And watch how that single change begins to reshape your entire financial trajectory.",

    "time is more valuable than money": "Most people spend their entire lives treating time as though it is unlimited and money as though it is the most valuable thing in the world. But this is completely backwards. You can always earn more money. You cannot get back a single minute of time once it passes. Every hour spent mindlessly scrolling is an hour that could have been used learning a skill that generates income. Every year spent delaying investing is a year of compound growth lost forever. Wealthy people protect their time obsessively because they understand it is their actual scarcest resource. They outsource tasks that waste their time. They say no to commitments that do not align with their goals. They invest time in learning and building instead of consuming and reacting. Treat your time as your most valuable financial asset because it genuinely is. Spend it as deliberately and intentionally as you would spend your last dollar.",

    "stop wasting energy on the wrong things": "You have a limited amount of mental and emotional energy every single day and most people waste the majority of it on things that will never move their financial life forward. Overthinking decisions that do not matter. Worrying about things completely outside their control. Comparing themselves to others online. Arguing about things that do not build anything. None of this creates wealth. But it drains the focus and energy you need to actually make progress. Successful wealthy people are almost obsessively selective about where they direct their attention and energy. They focus on actions that compound. Learning skills that pay. Building relationships that create opportunity. Making financial decisions that grow their wealth. Energy is limited and non renewable each day. Where you consistently direct it determines your results over time. Audit where your mental energy goes daily and aggressively redirect it toward actions that actually build your financial future.",

    "think bigger and your life expands": "Most people limit their financial results before they even take their first action by thinking too small about what is possible for them. They aim for tiny goals because tiny goals feel safe and achievable. But small thinking creates small actions which create small results which confirm the belief that nothing bigger is possible. It becomes a self fulfilling cycle of financial limitation. Big thinking works completely differently. When you genuinely believe that building significant wealth is possible for someone with your background and starting point your actions change. Your decisions change. You invest instead of spending because you can see the wealthy future you are building. You learn instead of scrolling because you know knowledge pays real returns. Think about what your financial life could look like in twenty years if you made excellent decisions consistently starting today. Then let that vision drive every financial choice you make from this moment forward.",

    "distractions are stealing your financial future": "Distractions are not just annoying inconveniences. They are actively stealing the time and focus you need to build financial freedom. Every notification that pulls your attention costs you far more than the seconds it takes to check it. Deep focused work on anything valuable requires extended periods of uninterrupted concentration. Building financial knowledge takes sustained attention. Learning investment strategies takes focused study. Building income producing skills takes distraction free practice. But most people live in a constant state of fractured attention jumping from notification to scroll to conversation without ever going deep enough into anything to develop real financial capability. The people building wealth around you are not smarter. They have simply learned to protect their attention aggressively. Remove notifications from your phone. Schedule time specifically for financial learning. Guard your focus like the financial asset it truly is because every distraction you allow is directly costing you future wealth.",

    "control your emotions or they control your money": "Your emotions are the greatest threat to your financial future and most people never learn to manage them deliberately. Impulse financial decisions made in moments of excitement or fear or boredom are responsible for more destroyed wealth than any market crash in history. You see markets falling and panic sells. You see a deal and impulse buys. You feel stressed and emotionally spends to feel better temporarily. Every one of these emotional reactions moves money away from your future. Wealthy investors have learned to create distance between their emotional reactions and their financial decisions. They do not react to market movements. They follow a predetermined plan. They pause before significant purchases. They separate how they feel in any given moment from what their long term financial strategy requires them to do. Control your emotional responses to money and you will make better financial decisions in every single situation you face.",

    "deep focus creates results faster than anything else": "In a world where almost everyone is distracted almost all of the time the ability to focus deeply on one thing has become one of the rarest and most financially valuable skills you can develop. When you can sit with a single important task for two or three uninterrupted hours without checking your phone or switching between activities you produce results that would take a distracted person an entire day. This means learning investment strategies faster. Building income generating skills faster. Making better financial decisions because you have thought them through completely. Most people never experience what genuine deep focus feels like because they reach for distraction the moment any task becomes slightly uncomfortable. But financial capability is built in those uncomfortable focused moments. Develop the habit of protecting blocks of time for deep focused financial learning and building. The compound effect of this single habit on your wealth over years is extraordinary.",

    "smart risks create opportunity and growth": "Playing it completely safe with your money might feel responsible but it is actually one of the riskiest financial strategies that exists. When you keep all your money in savings accounts earning almost nothing inflation destroys its purchasing power year after year. When you never invest because markets feel scary you miss decades of compound growth that cannot be recovered. When you never develop new income skills because learning feels risky you stay trapped at the same income level indefinitely. Real financial growth requires taking calculated intelligent risks. Not reckless gambling. But thoughtful investments in index funds. In developing valuable skills. In building things that could generate additional income. Every wealthy person took risks that felt uncomfortable at the time. They invested when uncertain. They built when success was not guaranteed. Smart risks are not the opposite of financial security. Over long time horizons they are actually the path to it.",

    "failure teaches what success never could": "Most people avoid failure so aggressively that they never learn the lessons that only failure can teach. They do not start investing because they fear making wrong decisions. They do not build additional income streams because they fear failure. They do not take any financial risks because the possibility of being wrong feels worse than the certainty of staying stuck. But every significant financial lesson you will ever learn comes from trying something imperfect and adjusting based on what happens. The investors who navigate market downturns best are those who have experienced downturns before. The entrepreneurs who build profitable businesses are those who failed at previous attempts and learned from them. Failure is not the opposite of financial success. It is the education system through which financial success is actually built. Make small controlled financial mistakes early. Learn aggressively from every one of them. And use those lessons to make better decisions for the rest of your financial life.",

    "keep going because most people quit too early": "The single most common reason people fail to build the financial life they want is that they stop too early. Progress in building wealth is always slow and almost invisible at the beginning. You invest for months and the account barely moves. You develop a new income skill and it does not pay off immediately. You change your financial habits and nothing dramatic happens right away. This is exactly when most people quit. They decide it is not working and they stop. But this is precisely when continuing is most important. Compound growth is exponential not linear. The early years produce small results. The later years produce extraordinary results. Every person who quit their investment plan in year three missed the explosive growth that happened in years ten through twenty. Do not stop. Do not let slow early progress convince you that your consistent financial efforts are not working. They are working. Keep going and let time prove it.",
}

def pick_topic() -> str:
    """Pick a random topic each run for variety."""
    return random.choice(FINANCE_TOPICS)

def generate_script(topic: str) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if api_key:
        result = _gemini_script(topic, api_key)
        if result:
            return result
    # Use topic-specific viral script if available
    if topic in VIRAL_SCRIPTS:
        return VIRAL_SCRIPTS[topic]
    # Generic fallback
    return random.choice(list(VIRAL_SCRIPTS.values()))

def _gemini_script(topic: str, api_key: str) -> str:
    try:
        import requests
        prompt = f"{SYSTEM_PROMPT}\n\nWrite a YouTube Shorts script about: {topic}"
        url  = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
        body = {"contents": [{"parts": [{"text": prompt}]}]}
        resp = requests.post(url, json=body, timeout=30)
        resp.raise_for_status()
        return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
    except Exception as e:
        log.warning(f"Gemini failed ({e}), using fallback")
        return None
